{* <auto-generated>
 *  automatically generated by the FlatBuffers compiler, do not modify
 * </auto-generated> *}

unit Display;

interface

uses
  System.SysUtils, ByteBuffer, Struct, FlatbufferObject, Offset, FlatBufferBuilder, Pixel;

type
  {* Display struct *}
  TDisplay = record
  private
    FStruct: TStruct;
    function GetByteBuffer: TByteBuffer;
  public
    constructor Create(_i: Integer; _bb: TByteBuffer);
    procedure __init(_i: Integer; _bb: TByteBuffer);
    function __assign(_i: Integer; _bb: TByteBuffer): TDisplay;

    property ByteBuffer: TByteBuffer read GetByteBuffer;

    function Content(j: Integer): TPixel;

    class function CreateDisplay(builder: TFlatBufferBuilder; const content_R: TArray<Byte>; const content_G: TArray<Byte>; const content_B: TArray<Byte>): TOffset<TDisplay>; static;
  end;

implementation

{ TDisplay }

constructor TDisplay.Create(_i: Integer; _bb: TByteBuffer);
begin
  __init(_i, _bb);
end;

function TDisplay.GetByteBuffer: TByteBuffer;
begin
  Result := FStruct.bb;
end;

procedure TDisplay.__init(_i: Integer; _bb: TByteBuffer);
begin
  FStruct := TStruct.Create(_i, _bb);
end;

function TDisplay.__assign(_i: Integer; _bb: TByteBuffer): TDisplay;
begin
  __init(_i, _bb);
  Result := Self;
end;

function TDisplay.Content(j: Integer): TPixel;
var
  pixel: TPixel;
begin
  Result := pixel.__assign(FStruct.bb_pos + 0 + j * 3, FStruct.bb);
end;

class function TDisplay.CreateDisplay(builder: TFlatBufferBuilder; const content_R: TArray<Byte>; const content_G: TArray<Byte>; const content_B: TArray<Byte>): TOffset<TDisplay>;
var
  _idx0: Integer;
begin
  builder.Prep(1, 192);
  for _idx0 := 64 downto 1 do
  begin
    builder.Prep(1, 3);
    builder.PutByte(content_B[_idx0 - 1]);
    builder.PutByte(content_G[_idx0 - 1]);
    builder.PutByte(content_R[_idx0 - 1]);
  end;
  Result := TOffset<TDisplay>.Create(builder.GetOffset);
end;

end.
