{* <auto-generated>
 *  automatically generated by the FlatBuffers compiler, do not modify
 * </auto-generated> *}

unit Message;

interface

uses
  System.SysUtils, ByteBuffer, Table, FlatbufferObject, Offset, FlatBufferBuilder,
  FlatBufferConstants, FlatBufferVerify, MessageId, Display;

type
  {* Message table *}
  TMessage = record
  private
    FTable: TTable;
    function GetByteBuffer: TByteBuffer;
  public
    procedure __init(_i: Integer; _bb: TByteBuffer);
    function __assign(_i: Integer; _bb: TByteBuffer): TMessage;

    property ByteBuffer: TByteBuffer read GetByteBuffer;

    class procedure ValidateVersion; static;
    class function GetRootAsMessage(_bb: TByteBuffer): TMessage; overload; static;
    class function GetRootAsMessage(_bb: TByteBuffer; obj: TMessage): TMessage; overload; static;
    class function VerifyMessage(_bb: TByteBuffer): Boolean; static;

    function GetId: TMessageId;
    function GetDisplay: TDisplay;

    property Id: TMessageId read GetId;
    property Display: TDisplay read GetDisplay;

    class procedure StartMessage(builder: TFlatBufferBuilder); static;
    class procedure AddId(builder: TFlatBufferBuilder; id: TMessageId); static;
    class procedure AddDisplay(builder: TFlatBufferBuilder; displayOffset: TOffset<TDisplay>); static;
    class function EndMessage(builder: TFlatBufferBuilder): TOffset<TMessage>; static;
    class procedure FinishMessageBuffer(builder: TFlatBufferBuilder; offset: TOffset<TMessage>); static;
    class procedure FinishSizePrefixedMessageBuffer(builder: TFlatBufferBuilder; offset: TOffset<TMessage>); static;
  end;

  {* Message verification class *}
  TMessageVerify = class
  public
    class function Verify(verifier: TVerifier; tablePos: Cardinal): Boolean; static;
  end;

implementation

{ TMessage }

function TMessage.GetByteBuffer: TByteBuffer;
begin
  Result := FTable.bb;
end;

procedure TMessage.__init(_i: Integer; _bb: TByteBuffer);
begin
  FTable := TTable.Create(_i, _bb);
end;

function TMessage.__assign(_i: Integer; _bb: TByteBuffer): TMessage;
begin
  __init(_i, _bb);
  Result := Self;
end;

class procedure TMessage.ValidateVersion;
begin
  TFlatBufferConstants.FLATBUFFERS_25_9_23;
end;

class function TMessage.GetRootAsMessage(_bb: TByteBuffer): TMessage;
var
  obj: TMessage;
begin
  Result := GetRootAsMessage(_bb, obj);
end;

class function TMessage.GetRootAsMessage(_bb: TByteBuffer; obj: TMessage): TMessage;
begin
  Result := obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb);
end;

class function TMessage.VerifyMessage(_bb: TByteBuffer): Boolean;
var
  verifier: TVerifier;
begin
  verifier := TVerifier.Create(_bb);
  try
    Result := verifier.VerifyBuffer('', False, TMessageVerify.Verify);
  finally
    verifier.Free;
  end;
end;

function TMessage.GetId: TMessageId;
var
  o: Integer;
begin
  o := FTable.__offset(4);
  if o <> 0 then
    Result := TMessageId(FTable.bb.GetSbyte(o + FTable.bb_pos))
  else
    Result := FullDisplay;
end;

function TMessage.GetDisplay: TDisplay;
var
  o: Integer;
  display: TDisplay;
begin
  o := FTable.__offset(6);
  if o <> 0 then
  begin
    display := TDisplay.Create(o + FTable.bb_pos, FTable.bb);
    Result := display;
  end
  else
  begin
    Result := TDisplay.Create(0, nil);
  end;
end;

class procedure TMessage.StartMessage(builder: TFlatBufferBuilder);
begin
  builder.StartTable(2);
end;

class procedure TMessage.AddId(builder: TFlatBufferBuilder; id: TMessageId);
begin
  builder.AddSbyte(0, ShortInt(id), 0);
end;

class procedure TMessage.AddDisplay(builder: TFlatBufferBuilder; displayOffset: TOffset<TDisplay>);
begin
  builder.AddStruct(1, displayOffset.Value, 0);
end;

class function TMessage.EndMessage(builder: TFlatBufferBuilder): TOffset<TMessage>;
var
  o: Integer;
begin
  o := builder.EndTable;
  Result := TOffset<TMessage>.Create(o);
end;

class procedure TMessage.FinishMessageBuffer(builder: TFlatBufferBuilder; offset: TOffset<TMessage>);
begin
  builder.Finish(offset.Value);
end;

class procedure TMessage.FinishSizePrefixedMessageBuffer(builder: TFlatBufferBuilder; offset: TOffset<TMessage>);
begin
  builder.FinishSizePrefixed(offset.Value);
end;

class function TMessageVerify.Verify(verifier: TVerifier; tablePos: Cardinal): Boolean;
begin
  Result := verifier.VerifyTableStart(tablePos) and
            verifier.VerifyField(tablePos, 4 {Id}, 1 {TMessageId}, 1, False) and
            verifier.VerifyField(tablePos, 6 {Display}, 192 {TDisplay}, 1, False) and
            verifier.VerifyTableEnd(tablePos);
end;

end.
