{* <auto-generated>
 *  automatically generated by the FlatBuffers compiler, do not modify
 * </auto-generated> *}

unit MessageId;

interface

type
  {* MessageId enum *}
  TMessageId = ShortInt;
  
const
  FullDisplay: TMessageId = 0;

implementation

end.
