{* <auto-generated>
 *  automatically generated by the FlatBuffers compiler, do not modify
 * </auto-generated> *}

unit Pixel;

interface

uses
  System.SysUtils, ByteBuffer, Struct, FlatbufferObject, Offset, FlatBufferBuilder;

type
  {* Pixel struct *}
  TPixel = record
  private
    FStruct: TStruct;
    function GetByteBuffer: TByteBuffer;
  public
    constructor Create(_i: Integer; _bb: TByteBuffer);
    procedure __init(_i: Integer; _bb: TByteBuffer);
    function __assign(_i: Integer; _bb: TByteBuffer): TPixel;

    property ByteBuffer: TByteBuffer read GetByteBuffer;

    function GetR: Byte;
    function GetG: Byte;
    function GetB: Byte;

    property R: Byte read GetR;
    property G: Byte read GetG;
    property B: Byte read GetB;

    class function CreatePixel(builder: TFlatBufferBuilder; R: Byte; G: Byte; B: Byte): TOffset<TPixel>; static;
  end;

implementation

{ TPixel }

constructor TPixel.Create(_i: Integer; _bb: TByteBuffer);
begin
  __init(_i, _bb);
end;

function TPixel.GetByteBuffer: TByteBuffer;
begin
  Result := FStruct.bb;
end;

procedure TPixel.__init(_i: Integer; _bb: TByteBuffer);
begin
  FStruct := TStruct.Create(_i, _bb);
end;

function TPixel.__assign(_i: Integer; _bb: TByteBuffer): TPixel;
begin
  __init(_i, _bb);
  Result := Self;
end;

function TPixel.GetR: Byte;
begin
  Result := FStruct.bb.Get(FStruct.bb_pos + 0);
end;

function TPixel.GetG: Byte;
begin
  Result := FStruct.bb.Get(FStruct.bb_pos + 1);
end;

function TPixel.GetB: Byte;
begin
  Result := FStruct.bb.Get(FStruct.bb_pos + 2);
end;

class function TPixel.CreatePixel(builder: TFlatBufferBuilder; R: Byte; G: Byte; B: Byte): TOffset<TPixel>;
begin
  builder.Prep(1, 3);
  builder.PutByte(B);
  builder.PutByte(G);
  builder.PutByte(R);
  Result := TOffset<TPixel>.Create(builder.GetOffset);
end;

end.
